### ISSUE TITLE
stackOverflow onBlockBreak

### ISSUE THREAD

**Issue by Yoghurt4C** [hea3ven/DulceDeLeche#17]
```java.lang.NoSuchMethodError: net.minecraft.class_1657.method_5745(DFZ)Lnet/minecraft/class_239;
        at com.hea3ven.dulcedeleche.modules.enchantments.BlockBreakHandlerKt.onBlockBreak(blockBreakHandler.kt:18)
        at net.minecraft.class_3225.handler$onBlockBreak$zei000(class_3225.java:1555)
        at net.minecraft.class_3225.method_14266(class_3225.java:232)
        at net.minecraft.class_3225.method_14258(class_3225.java:173)
        at net.minecraft.class_3244.method_12066(class_3244.java:918)
        at net.minecraft.class_2846.method_12361(class_2846.java:40)
        at net.minecraft.class_2846.method_11054(class_2846.java:10)
        at net.minecraft.class_2600.method_11072(class_2600.java:15)
        at net.minecraft.class_3738.run(class_3738.java:18)
        at net.minecraft.class_1255.method_18859(class_1255.java:135)
        at net.minecraft.class_4093.method_18859(class_4093.java:23)
        at net.minecraft.class_1255.method_16075(class_1255.java:114)
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:702)
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:696)
        at net.minecraft.class_1255.method_18857(class_1255.java:123)
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:681)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636)
        at java.lang.Thread.run(Thread.java:748)
```
dulcedeleche-1.2.2-30

**Comment by hea3ven** [comment]
what minecraft and fabric versions are you using? what were you doing when it happened?

**Comment by Yoghurt4C** [comment]
1.14
loader-0.4.4+build.139

crash happened when someone tried using an `area`-enchanted pickaxe
